services:
  gateway:
    build:
      context: ./gateway-service
    container_name: micro-gateway
    restart: unless-stopped
    networks:
      - micro-network
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      GATEWAY_SERVICE_PORT: 3000
      AUTH_SERVICE_URL: http://auth:3000
      USER_SERVICE_URL: http://user:3000
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    depends_on:
      auth:
        condition: service_started
      user:
        condition: service_started

  auth:
    build:
      context: ./auth-service
    container_name: micro-auth
    restart: unless-stopped
    networks:
      - micro-network
    ports:
      - "3001:3000"
    environment:
      PORT: 3000
      AUTH_SERVICE_PORT: 3000
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}

  user:
    build:
      context: ./user-service
    container_name: micro-user
    restart: unless-stopped
    networks:
      - micro-network
    ports:
      - "3002:3000"
    environment:
      PORT: 3000
      USER_SERVICE_PORT: 3000
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}

  frontend:
    build:
      context: ./reactjs/frontend
    container_name: micro-frontend
    restart: unless-stopped
    networks:
      - micro-network
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE: http://localhost:3000
    depends_on:
      gateway:
        condition: service_started

networks:
  micro-network:
    driver: bridge